---
title: "Simplified coefficient tables"
author: "Kim Cressman"
date: "2/2/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(patchwork)
files_allRes <- c("AllRes_TankAndISCO", "AllRes_TankOnly")
files_indRes <- c("IndRes_TankAndISCO", "IndRes_TankOnly")
```

# Individual Reserve Models  

## Tank and ISCO  

```{r}
dat <- read_csv(here::here("model_coeffs",
                           paste0(files_indRes[[1]], ".csv")))

dat_cleaner <- dat %>% 
    select(Reserve, model, AICc, R.2, prediction_error = pred_test_error,
           sensor_rfu, fdom_qsu, turb, temp, season,
           everything()) %>% 
    mutate(across(c(AICc, prediction_error), round, 2),
           across(c(R.2, sensor_rfu), round, 3),
           across(c(fdom_qsu, turb, temp), round, 4),
           across(c(X.Intercept.:fdom_qsu.sensor_rfu.turb), 
                  ~case_when(. < 0 ~ "-",
                             . >= 0 ~ "+")))

dat_ind_ti <- dat_cleaner
```

```{r}
write_csv(dat_cleaner, here::here("model_coeffs", 
                                  paste0(files_indRes[[1]], "_clean.csv")),
          na = "")
```


## Tank Only  

```{r}
dat <- read_csv(here::here("model_coeffs",
                           paste0(files_indRes[[2]], ".csv")))

dat_cleaner <- dat %>% 
    select(Reserve, model, AICc, R.2, prediction_error = pred_test_error,
           sensor_rfu, fdom_qsu, turb, temp, season,
           everything()) %>% 
    mutate(across(c(AICc, prediction_error), round, 2),
           across(c(R.2, sensor_rfu), round, 3),
           across(c(fdom_qsu, turb, temp), round, 4),
           across(c(X.Intercept.:fdom_qsu.sensor_rfu.turb), 
                  ~case_when(. < 0 ~ "-",
                             . >= 0 ~ "+")))

dat_ind_t <- dat_cleaner
```

```{r}
write_csv(dat_cleaner, here::here("model_coeffs", 
                                  paste0(files_indRes[[2]], "_clean.csv")),
          na = "")
```


## Combine data frames so I can facet   

This is theoretically easier but will cause problems with labels and scales.....

```{r}
dat_ind_t$data_source <- "Tank Only"
dat_ind_ti$data_source <- "Tank + ISCO"

dat_all <- bind_rows(dat_ind_t, dat_ind_ti)
```

```{r}
rsq <- ggplot(dat_all,
       aes(x = Reserve,
           y = R.2,
           color = model,
           shape = model),
       size = 2,
       alpha = 0.7) +
  geom_point() +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_color_brewer(palette = "Set1") +
  labs(x = NULL, y = expression("R"^"2"))

err <- ggplot(dat_all,
       aes(x = Reserve,
           y = prediction_error,
           color = model,
           shape = model),
       size = 2,
       alpha = 0.7) +
  geom_point() +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_color_brewer(palette = "Set1") +
  labs(x = NULL, y = "Median Absolute \nPrediction Error")
```


```{r}
# try adding labels with some code from the stackoverflow answer
# https://stackoverflow.com/a/60354844
col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank + ISCO") + theme_void() 

col2 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank Only") + theme_void() 

(col1 + col2) / rsq / err +
  plot_layout(guides = 'collect',
              heights = c(1, 3, 3))
```



# All Reserves  

Need to get this into the data frame above, and do that plot.  

Combined model will get a reserve code: 'ALL'  

```{r}
dat <- read_csv(here::here("model_coeffs",
                           paste0(files_allRes[[1]], ".csv")))

dat_cleaner <- dat %>% 
    select(model, AICc, R.2, prediction_error = pred_test_error,
           sensor_rfu, fdom_qsu, turb, temp, season,
           everything()) %>% 
    mutate(across(c(AICc, prediction_error), round, 2),
           across(c(R.2, sensor_rfu), round, 3),
           across(c(fdom_qsu, turb, temp), round, 4),
           across(c(X.Intercept.:fdom_qsu.sensor_rfu.turb), 
                  ~case_when(. < 0 ~ "-",
                             . >= 0 ~ "+")))

all_ti <- dat_cleaner
```

```{r}
write_csv(dat_cleaner, here::here("model_coeffs", 
                                  paste0(files_allRes[[1]], "_clean.csv")),
          na = "")
```


```{r}
dat <- read_csv(here::here("model_coeffs",
                           paste0(files_allRes[[2]], ".csv")))

dat_cleaner <- dat %>% 
    select(model, AICc, R.2, prediction_error = pred_test_error,
           sensor_rfu, fdom_qsu, turb, temp, season,
           everything()) %>% 
    mutate(across(c(AICc, prediction_error), round, 2),
           across(c(R.2, sensor_rfu), round, 3),
           across(c(fdom_qsu, turb, temp), round, 4),
           across(c(X.Intercept.:fdom_qsu.sensor_rfu.turb), 
                  ~case_when(. < 0 ~ "-",
                             . >= 0 ~ "+")))

all_t <- dat_cleaner
```

```{r}
write_csv(dat_cleaner, here::here("model_coeffs", 
                                  paste0(files_allRes[[2]], "_clean.csv")),
          na = "")
```


```{r}
all_t <- all_t %>% 
  mutate(model = case_when(model == 'rfu_only' ~ 'rfu_only',
                           model == 'top.ols' ~ 'best_AIC',
                           model == 'no.fdom.ols' ~ 'no_fdom_ols'),
         data_source = "Tank Only",
         Reserve = 'ALL')

all_ti <- all_ti %>% 
  mutate(model = case_when(model == 'rfu_only' ~ 'rfu_only',
                           model == 'top.ols' ~ 'best_AIC',
                           model == 'no.fdom.ols' ~ 'no_fdom_ols'),
         data_source = "Tank + ISCO",
         Reserve = 'ALL')

dat_all <- bind_rows(dat_all, all_t, all_ti)
```

```{r}
rsq <- ggplot(dat_all,
       aes(x = Reserve,
           y = R.2,
           color = model,
           shape = model),
       size = 2,
       alpha = 0.7) +
  geom_point() +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_color_brewer(palette = "Set1") +
  labs(x = NULL, y = expression("R"^"2"))

err <- ggplot(dat_all,
       aes(x = Reserve,
           y = prediction_error,
           color = model,
           shape = model),
       size = 3,
       alpha = 0.7) +
  geom_point() +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_color_brewer(palette = "Set1") +
  labs(x = NULL, y = "Median Absolute \nPrediction Error")
```


```{r}
# try adding labels with some code from the stackoverflow answer
# https://stackoverflow.com/a/60354844
col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank + ISCO") + theme_void() 

col2 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank Only") + theme_void() 

(col1 + col2) / rsq / err +
  plot_layout(guides = 'collect',
              heights = c(1, 3, 3))
```