---
output: html_document
---

```{r, message = FALSE, warning = FALSE}
files_allRes <- c("AllRes_TankAndISCO", "AllRes_TankOnly")
files_indRes <- c("IndRes_TankAndISCO", "IndRes_TankOnly")
```

```{r}
# read in Individual Reserve data frames
dat_ind_ti <- read_csv(here::here("model_coeffs",
                           paste0(files_indRes[[1]], ".csv")))

dat_ind_t <- read_csv(here::here("model_coeffs",
                           paste0(files_indRes[[2]], ".csv")))

# combine for faceting
dat_ind_t$data_source <- "Tank Only"
dat_ind_ti$data_source <- "Tank + ISCO"

dat_all <- bind_rows(dat_ind_t, dat_ind_ti)
```


```{r}
# all reserves
all_ti <- read_csv(here::here("model_coeffs",
                           paste0(files_allRes[[1]], ".csv")))

all_t <- read_csv(here::here("model_coeffs",
                           paste0(files_allRes[[2]], ".csv")))
```


```{r}
all_t <- all_t %>% 
  mutate(data_source = "Tank Only",
         Reserve = 'ALL')

all_ti <- all_ti %>% 
  mutate(data_source = "Tank + ISCO",
         Reserve = 'ALL')

dat_all <- bind_rows(dat_all, all_t, all_ti)
```

```{r}
rsq <- ggplot(dat_all,
       aes(x = Reserve,
           y = R.2,
           color = model,
           shape = model)) +
  geom_point(size = 3,
             alpha = 0.8) +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_shape_manual(values = 1:15) +
  labs(x = NULL, y = expression("R"^"2"))

err <- ggplot(dat_all,
       aes(x = Reserve,
           y = prediction_error,
           color = model,
           shape = model)) +
  geom_point(size = 3,
             alpha = 0.8) +
  facet_wrap(~data_source) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_blank()) +
  scale_shape_manual(values = 1:15) +
  labs(x = NULL, y = "Median Absolute \nPrediction Error")
```


```{r}
# try adding labels with some code from the stackoverflow answer
# https://stackoverflow.com/a/60354844
col1 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank + ISCO") + theme_void() 

col2 <- ggplot() + annotate(geom = 'text', x=1, y=1, label="Tank Only") + theme_void() 

# use colorblind friendly palette; from khroma::scale_color_okabeito
# even though I did shapes already!
# colors <- scale_color_manual(values = c("#009E73", "#D55E00", "#CC79A7"))

# from khroma::muted
# colors <- scale_color_manual(values = c("#332288", "#882255", "#44AA99"))


# from khroma::vibrant
colors <- scale_color_manual(values = rep(c("#0077BB", "#CC3311", "#009988"), 4))

(col1 + col2) / (rsq + colors) / (err + colors) +
  plot_layout(guides = 'collect',
              heights = c(1, 3, 3))
```

```{r}
ggsave(here::here("model_coeffs", "diagnostic_plot_updated_lotsamodels.png"),
       width = 8.5, height = 6.5, units = "in")
```

